# Generated by Django 5.0.2 on 2024-02-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit',
            field=models.IntegerField(),
        ),
    ]
