# Generated by Django 5.0.2 on 2024-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_alter_costumer_credit_alter_seller_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='innercharge',
            name='amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registrationlog',
            name='credit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='amount',
            field=models.FloatField(default=None, null=True),
        ),
    ]
