# Generated by Django 5.0.2 on 2024-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0003_alter_costumer_credit_alter_innercharge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='credit',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='innercharge',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrationlog',
            name='credit',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=25, null=True),
        ),
    ]
